# Generated by Django 3.2.8 on 2021-11-15 12:37

import advito.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0002_auto_20211010_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профели'},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[advito.validators.validate_date_edit], verbose_name='дата изменения'),
        ),
    ]
