# Generated by Django 3.2.8 on 2021-11-17 15:25

import advito.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0003_auto_20211115_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, validators=[advito.validators.validate_date_edit], verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
